### ISSUE TITLE
Error: COLLECTION_NAME not set in .env file.

### ISSUE THREAD

**Issue by CryptoLibertus** [mckaywrigley/ai-brainstore#1]
I did create a .env.local file with the collection name. Why is this error throwing?

**Comment by nattyraz** [comment]
Hi, i got the same =Error: COLLECTION_NAME not set in .env file. 
but if you keep = COLLECTION_NAME=ai-brainstore # name for your brainsstore & just (.env) File & delete (. local ) it work !!! 


but i got a new message = Insuffient memories. Now learning... I made a mistake. Trying again...I made a mistake. Trying again...I made a mistake. Trying again...I made a mistake. Trying again...I made a mistake. Trying again...I made a mistake. 

it not find out .....

**Comment by MKLVN** [comment]
@CryptoLibertus @nattyraz I edited package.json "scripts" section with the following snippet and it worked:
```
"scripts": {
  "agent": "npx tsc && node -r dotenv/config dist/index.js dotenv_config_path=.env.local"
},
```

**Comment by CryptoLibertus** [comment]
> @CryptoLibertus @nattyraz I edited package.json "scripts" section with the following snippet and it worked:
> 
> ```
> "scripts": {
>   "agent": "npx tsc && node -r dotenv/config dist/index.js dotenv_config_path=.env.local"
> },
> ```

This worked for me. Thanks.
